#!/usr/bin/env node

const {
    readFileSync
} = require('fs')
const {
    join
} = require('path')
const {
    logError
} = require('./helpers')

const pkgPath = join(process.cwd(), 'package.json')
try {
    const package = require(pkgPath)

    require('yargs/yargs')(process.argv.slice(2))
        .scriptName('elf')
        .commandDir('cmds')
        .demandCommand()
        .help()
        .fail((msg, err, yargs) => {
            if (err) throw err
            logError(msg)
            process.exit(1)
        })
        .argv
} catch (err) {
    if (err.message.indexOf(pkgPath) > -1) {
        logError("Please run me from the project root!")
    }
    throw err
}