#!/usr/bin/env node

const {
    logError,
    changeToRoot,
    findConfig
} = require('./helpers')

// Make sure we're in the root
changeToRoot()

require('yargs/yargs')(process.argv.slice(2))
    .scriptName('elf')
    .commandDir('cmds')
    .demandCommand()
    .config(findConfig())
    .help()
    .fail((msg, err, yargs) => {
        if (err) throw err
        logError(msg)
        process.exit(1)
    })
    .argv