ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
ifndef::env-github[]
:tip-caption: 💡
:note-caption: ℹ
:important-caption: ❗
:caution-caption: 🔥
:warning-caption: ⚠
endif::[]

= Elf, a CLI for Elfin

In the course of using link:https://github.com/11in/elfin[Elfin] you may encounter some tasks that you feel could be automated to save you time.
Fortunately there is a friendly elf here to...helf you.

If you find yourself needing a particular tool in the CLI, feel free to link:https://github.com/11in/elf/pulls[submit a PR] or a link:https://github.com/11in/elf/issues/new[feature request issue].

== Installation

While you can install this locally, by far the most useful install location is "global".

[source,bash]
----
$ npm i -g 11in/elf
----

== Usage

Once elf is installed globally, you can run it like this:

[source,bash]
----
$ elf
----

[WARNING]
====
Elf will only work if you run it in the root of an Elfin project.
====

== Tools

=== scaffold

`elf scaffold` helps you to quickly scaffold extentions to 11ty--and eventually other things as well, like templates, partials, etc.

All current `scaffold` types come with default stub files that add essentially useless placeholder code.
If you want to use your own stubs, you can do so by passing a path to the `--stub` option when calling the command:

[source,bash]
----
elf scaffold collection ships --stub ./collections.stub
----

[NOTE]
====
Your custom stubs can contain whatever you like, but they will be parsed as link:https://github.com/janl/mustache.js[mustache] templates, and will be passed all the arguments the function recieved from the command line. 
That means you can do something like this:

[source,javascript]
----
// custom.stub
console.log('{{ custom_arg }}')
----

[source,bash]
----
$ elf scaffold filter example_filter --stub ./custom.stub --custom_arg 'Hello there'
----

[source,js]
----
// filters/example_filter.js
console.log('Hello there')
----
====

Currently, `scaffold` can create three types of things:

`elf scaffold collection`:: Creates an link:https://www.11ty.dev/docs/collections/[11ty collection].
You can optionally pass an argument to `--glob` to define the glob used to collect files, i.e. `+elf scaffold collection ships --glob 'ships/**/*.md'+`.
If you don't, the collection generated will get all files.

`elf scaffold filter`:: Creates an link:https://www.11ty.dev/docs/filters/[11ty filter]
(specifically a Universal Filter).
Read more about link:filters.adoc[Elfin's filters].

`elf scaffold shortcode`:: Create an link:https://www.11ty.dev/docs/shortcodes/[11ty shortcode]
(specifically a Universal Shortcode).
Read more about link:shortcodes.adoc[Elfin's filters].

For more information on any of these things, just call them with the `--help` argument:

[source,bash]
----
elf scaffold collection --help
----
