= scaffold

Scaffold is used to generate extensions to Elfin, like filters, collections, etc.

[NOTE]
====
`scaffold` can also be called in its short form, as `scf`.
====

.Options
- `--stub`, `-s`
+
All the scaffolds that ship with Elf include their own stub files.
If these aren't doing what you want, this option allow syou to specify your own custom stub file.
+
Stubs use link:https://github.com/janl/mustache.js/[mustache.js] for templating.
All options and arguments passed to the command are also passed to the template when it is rendered, allowing for significant customization.
That means you can do something like this:
+
[source,javascript]
----
// custom.stub
console.log('{{ custom_arg }}')
----
+
[source,bash]
----
$ elf scaffold filter example_filter --stub ./custom.stub --custom_arg 'Hello there'
----
+
[source,js]
----
// filters/example_filter.js
console.log('Hello there')
----
+
`--stub` expects a string that is a path to your file.

- `--open`, `-o`
+
When this option is passed to a scaffold command, it wil attempt to open the relevant file(s) once they have been created.
Whether or not this works is somewhat dependent on what editor you use and how it was installed.

== filter

Creates an link:https://www.11ty.dev/docs/filters/[11ty filter]
(specifically a Universal Filter).

.Usage
[source,bash]
----
$ elf scaffold filter new_filter
$ elf scf filter new_filter
$ elf scf filter new_filter --stub ~/filter.stub --custom-argument 'custom value' -o
----

== shortcode 

Create an link:https://www.11ty.dev/docs/shortcodes/[11ty shortcode]
(specifically a Universal Shortcode).

.Usage
[source,bash]
----
$ elf scaffold shortcode new_shortcode
$ elf scf shortcode new_shortcode
$ elf scf shortcode new_shortcode --stub ~/shortcode.stub --custom-argument 'custom value' -o
----

== collection

Creates an link:https://www.11ty.dev/docs/collections/[11ty collection].
You can optionally pass an argument to `--glob` to define the glob used to collect files, i.e. `+elf scaffold collection ships --glob 'ships/**/*.md'+`.
If you don't, the collection generated will get all files.

.Options
- `--glob`, `-g`
+
This allows you to specify a string that will be inserted into the template as the link:https://www.11ty.dev/docs/collections/#getfilteredbyglob(-glob-)[glob used to select files] when building the collection.

.Usage
[source,bash]
----
$ elf scaffold collection new_collection
$ elf scf collection new_collection
$ elf scf collection new_collection --stub ~/collection.stub --custom-argument 'custom value' -o --glob 'new/**/*.md'
----

== generator

Creates a link:generate.adoc[generator] for Elf, but defined in your project's `elf.config.js`.

[IMPORTANT]
====
Part of the generator stub is used itself to generate stubs;
this means that we need to link:https://github.com/janl/mustache.js/#setting-in-templates[set custom delimiters] so that it can contain `{{ }}` without them being evaluated.

See link:../scaffold/stubs/generator.stub[generator.stub] for an example.
====

.Options
- `--desc`
+
A string that will be used as the description of the command.

- `--singular`
+
Used as the singular name of the entry.
+
i.e. If the name of your collection is `blog`, you might want single entries to be `post`: `elf scf generate blog --singular post`.

.Usage
[source,bash]
----
$ elf scaffold generate new_generator
$ elf scf generate new_generator
$ elf scf generate new_generator --stub ~/generator.stub --custom-argument 'custom value' -o --desc "A new collection" --singular "single"
----
